import { describe, expect, it } from "vitest";
import { EngineFormatter } from "./support/engineFormatter";
import { FragmentRepairer } from "./support/fragmentRepairer";
import { rangeCorpus } from "./support/rangeCorpus";
import { Settings } from "../settings";
import { TextXmlFormatter } from "../regexFormatter";

const settings = new Settings(EngineFormatter.baselineSettings);
const indentLength = settings.indentLength ?? 4;

/*
 * Task 8a: measure, do not fix. This suite is the scope document for the rest of task 8 - it
 * records, in a committed baseline, exactly where the range formatter and the engine disagree
 * today. A change in the report is a change in the range formatter's behavior and shows up as a
 * diff, which is the point: 8b and 8c are supposed to move that file only where they mean to.
 *
 * The engine is reached through FragmentRepairer, which encloses the selection in a synthetic root
 * - the only way a fragment gets past XmlDocument.LoadXml. Where that root cannot be built or the
 * engine refuses the result, the report says so instead of comparing, and those rows are the list
 * of cases the tree formatter has to serve on its own.
 */

/*
 * The engine joins lines with Environment.NewLine, so on windows-latest every multi-line result
 * comes back CRLF-joined while the range formatter always joins with "\n". Compared raw, every
 * case but the single-line ones would read as "differs" on CI and nowhere else. Line endings are
 * not what this suite measures - shape is - so both sides are read in LF.
 */
function withUnixNewlines(value: string): string {
    return value.replace(/\r\n/gu, "\n");
}

/** Every read of the engine goes through here, so nothing downstream ever meets a CRLF. */
async function engineOutput(document: string): Promise<string> {
    return withUnixNewlines(await EngineFormatter.format(document));
}

async function formatThroughEngine(fragment: string): Promise<string> {
    const repaired = FragmentRepairer.repair(fragment);
    if (repaired.rejection !== "") {
        return `[not delegable] ${repaired.rejection}`;
    }

    const result = await EngineFormatter.run(repaired.document);
    if (result.exitCode !== 0) {
        return `[engine rejects] ${EngineFormatter.describeFailure(result)}`;
    }

    return FragmentRepairer.stripSyntheticRoot(withUnixNewlines(result.stdout), indentLength);
}

function block(label: string, body: string): string {
    return `${label}\n\n\`\`\`xml\n${body}\n\`\`\`\n`;
}

describe("Range formatter vs the engine - recorded divergence baseline (task 8a)", () => {
    it("matches the committed baseline", async () => {
        const sections: string[] = [];
        let identicalCount = 0;
        let divergentCount = 0;
        let unreachableCount = 0;
        let unstableCount = 0;

        for (const entry of rangeCorpus) {
            const regexOutput = new TextXmlFormatter(settings).formatXmlPretty(entry.fragment);
            const engineOutput = await formatThroughEngine(entry.fragment);
            const isIdempotent = new TextXmlFormatter(settings).formatXmlPretty(regexOutput) === regexOutput;
            if (isIdempotent === false) {
                unstableCount++;
            }

            let verdict: string;
            if (engineOutput.startsWith("[")) {
                verdict = "engine unreachable - the tree formatter is on its own here";
                unreachableCount++;
            } else if (engineOutput === regexOutput) {
                verdict = "identical";
                identicalCount++;
            } else {
                verdict = "differs";
                divergentCount++;
            }

            sections.push([
                `## ${entry.name}`,
                "",
                `**${verdict}**` + (isIdempotent ? "" : " - and formatting it twice does not settle"),
                "",
                block("Selection:", entry.fragment),
                block("Range formatter today:", regexOutput),
                block("Engine, through a synthetic root:", engineOutput),
            ].join("\n"));
        }

        const report = [
            "# Range formatter divergence baseline",
            "",
            "Generated by `src/test/rangeDifferential.test.ts`. Do not edit by hand - run",
            "`pnpm exec vitest run -u` and review the diff.",
            "",
            `${rangeCorpus.length} selections: ${identicalCount} identical, ${divergentCount} differ, `
                + `${unreachableCount} the engine cannot be asked about.`,
            "",
            `Not idempotent under the range formatter - \`format(format(x))\` differs from `
                + `\`format(x)\`: ${unstableCount}.`,
            "",
            ...sections,
        ].join("\n");

        await expect(report.replace(/\r\n/gu, "\n")).toMatchFileSnapshot("./baselines/rangeFormatterDivergence.md");
    }, 120000);
});

/*
 * The findings that decide whether delegating to the engine is worth building, pinned as tests so
 * a later engine version cannot quietly change the answer.
 */
describe("Delegating a selection to the engine - what the synthetic root can and cannot do", () => {
    const wholeDocuments = [
        "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>",
        "<Root><!-- lead --><Child a=\"1\" b=\"2\">text</Child><Empty/><![CDATA[x]]></Root>",
        "<a><b><c><d><e>deep</e></d></c></b></a>",
    ];

    it.each(wholeDocuments)(
        "a synthetic root added and stripped reproduces the engine's own document formatting: %s",
        async document => {
            const direct = await engineOutput(document);
            const enclosed = await engineOutput(FragmentRepairer.repair(document).document);
            expect(FragmentRepairer.stripSyntheticRoot(enclosed, indentLength)).toBe(direct);
        },
        30000
    );

    it("formats a fragment whose namespace prefix is bound outside the selection", async () => {
        const repaired = FragmentRepairer.repair("<xsl:template match=\"/\"><xsl:text>x</xsl:text></xsl:template>");
        expect(repaired.syntheticPrefixes).toContain("xsl");

        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toBe("<xsl:template match=\"/\">\n    <xsl:text>x</xsl:text>\n</xsl:template>");
    }, 30000);

    /*
     * One xmlns per prefix puts the synthetic root past attributesInNewlineThreshold, so the
     * engine wraps the synthetic root's own start tag - and a stripper that assumes that root
     * occupies one line leaves two stray xmlns lines at the top of the user's selection.
     */
    it("strips a synthetic root whose own start tag wrapped over several lines", async () => {
        const repaired = FragmentRepairer.repair("<d:Grid x:Name=\"root\" m:Ignorable=\"d\"><d:Text/></d:Grid>");
        expect(repaired.syntheticPrefixes).toEqual(["d", "m", "x"]);

        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).not.toContain("prettyxml-synthetic");
        expect(formatted.split("\n")[0]).toBe("<d:Grid x:Name=\"root\"");
    }, 30000);

    it("keeps a prefix the fragment declares itself bound to the real namespace", async () => {
        const repaired = FragmentRepairer.repair("<a xmlns:p=\"urn:x\"><p:b/></a>");
        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toContain("xmlns:p=\"urn:x\"");
    }, 30000);

    it("refuses an unbalanced selection rather than inventing the missing tags", () => {
        expect(FragmentRepairer.repair("</b></a>").rejection).toContain("unbalanced");
        expect(FragmentRepairer.repair("<a><b>text").rejection).toContain("unbalanced");
    });

    it("refuses a selection that ends mid-tag", () => {
        expect(FragmentRepairer.repair("<a><b attr=\"v").rejection).toContain("mid-token");
    });

    it("cannot format a selection referencing an entity declared outside it", async () => {
        const repaired = FragmentRepairer.repair("<a>&myEntity;</a>");
        expect(repaired.rejection).toBe("");

        const result = await EngineFormatter.run(repaired.document);
        expect(result.exitCode).not.toBe(0);
        expect(EngineFormatter.describeFailure(result)).toBe("Reference to undeclared entity 'myEntity'.");
    }, 30000);

    /*
     * The engine normalizes an attribute value the user did not ask to have rewritten. That is
     * correct XML and wrong for a selection, and it is the strongest argument for the tree
     * formatter owning the default path: rule 1 says nothing is invented and nothing is deleted.
     */
    it("rewrites attribute value bytes that the range formatter leaves alone", async () => {
        const repaired = FragmentRepairer.repair("<a b=\"x>y\" c='say \"hi\"'/>");
        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toContain("&gt;");
        expect(formatted).toContain("&quot;");
    }, 30000);
});
