import { describe, expect, it } from "vitest";
import { EngineFormatter } from "./support/engineFormatter";
import { FragmentRepairer } from "./support/fragmentRepairer";
import { rangeCorpus } from "./support/rangeCorpus";
import { FormattingActionKind } from "../formattingActionKind";
import { ISettings, Settings } from "../settings";
import { TextXmlFormatter } from "../regexFormatter";

const settings = new Settings(EngineFormatter.baselineSettings);
const indentLength = settings.indentLength ?? 4;

/*
 * Task 8a: measure, do not fix. This suite is the scope document for the rest of task 8 - it
 * records, in a committed baseline, exactly where the range formatter and the engine disagree
 * today. A change in the report is a change in the range formatter's behavior and shows up as a
 * diff, which is the point: 8b and 8c are supposed to move that file only where they mean to.
 *
 * The engine is reached through FragmentRepairer, which encloses the selection in a synthetic root
 * - the only way a fragment gets past XmlDocument.LoadXml. Where that root cannot be built or the
 * engine refuses the result, the report says so instead of comparing, and those rows are the list
 * of cases the tree formatter has to serve on its own.
 */

/*
 * The engine joins lines with Environment.NewLine, so on windows-latest every multi-line result
 * comes back CRLF-joined while the range formatter always joins with "\n". Compared raw, every
 * case but the single-line ones would read as "differs" on CI and nowhere else. Line endings are
 * not what this suite measures - shape is - so both sides are read in LF.
 */
function withUnixNewlines(value: string): string {
    return value.replace(/\r\n/gu, "\n");
}

/** Every read of the engine goes through here, so nothing downstream ever meets a CRLF. */
async function engineOutput(document: string, formattingOptionOverrides: Partial<ISettings> = {}): Promise<string> {
    return withUnixNewlines(await EngineFormatter.format(document, FormattingActionKind.format, formattingOptionOverrides));
}

async function formatThroughEngine(fragment: string): Promise<string> {
    const repaired = FragmentRepairer.repair(fragment);
    if (repaired.rejection !== "") {
        return `[not delegable] ${repaired.rejection}`;
    }

    const result = await EngineFormatter.run(repaired.document);
    if (result.exitCode !== 0) {
        return `[engine rejects] ${EngineFormatter.describeFailure(result)}`;
    }

    return FragmentRepairer.stripSyntheticRoot(withUnixNewlines(result.stdout), indentLength);
}

function block(label: string, body: string): string {
    return `${label}\n\n\`\`\`xml\n${body}\n\`\`\`\n`;
}

describe("Range formatter vs the engine - recorded divergence baseline (task 8a)", () => {
    it("matches the committed baseline", async () => {
        const sections: string[] = [];
        let identicalCount = 0;
        let divergentCount = 0;
        let unreachableCount = 0;
        let unstableCount = 0;

        for (const entry of rangeCorpus) {
            const regexOutput = new TextXmlFormatter(settings).formatXmlPretty(entry.fragment);
            const engineOutput = await formatThroughEngine(entry.fragment);
            const isIdempotent = new TextXmlFormatter(settings).formatXmlPretty(regexOutput) === regexOutput;
            if (isIdempotent === false) {
                unstableCount++;
            }

            let verdict: string;
            if (engineOutput.startsWith("[")) {
                verdict = "engine unreachable - the tree formatter is on its own here";
                unreachableCount++;
            } else if (engineOutput === regexOutput) {
                verdict = "identical";
                identicalCount++;
            } else {
                verdict = "differs";
                divergentCount++;
            }

            sections.push([
                `## ${entry.name}`,
                "",
                `**${verdict}**` + (isIdempotent ? "" : " - and formatting it twice does not settle"),
                "",
                block("Selection:", entry.fragment),
                block("Range formatter today:", regexOutput),
                block("Engine, through a synthetic root:", engineOutput),
            ].join("\n"));
        }

        const report = [
            "# Range formatter divergence baseline",
            "",
            "Generated by `src/test/rangeDifferential.test.ts`. Do not edit by hand - run",
            "`pnpm exec vitest run -u` and review the diff.",
            "",
            `${rangeCorpus.length} selections: ${identicalCount} identical, ${divergentCount} differ, `
                + `${unreachableCount} the engine cannot be asked about.`,
            "",
            `Not idempotent under the range formatter - \`format(format(x))\` differs from `
                + `\`format(x)\`: ${unstableCount}.`,
            "",
            ...sections,
        ].join("\n");

        await expect(report.replace(/\r\n/gu, "\n")).toMatchFileSnapshot("./baselines/rangeFormatterDivergence.md");
    }, 120000);
});

// Three options the engine reads as one decision, so they are checked together.
describe("Attribute placement matches the engine (task 8d)", () => {
    const document = "<Root a=\"1\" b=\"2\"><Child x=\"1\"/><Child x=\"1\" y=\"2\" z=\"3\"><Leaf/></Child></Root>";
    const combinations: Partial<ISettings>[] = [];
    for (const positionFirstAttributeOnSameLine of [true, false]) {
        for (const positionAllAttributesOnFirstLine of [false, true]) {
            for (const attributesInNewlineThreshold of [1, 2]) {
                for (const indentLength of [4, 2]) {
                    combinations.push({
                        positionFirstAttributeOnSameLine,
                        positionAllAttributesOnFirstLine,
                        attributesInNewlineThreshold,
                        indentLength,
                    });
                }
            }
        }
    }

    it.each(combinations)("%o", async overrides => {
        const expected = await engineOutput(document, overrides);
        const rangeSettings = new Settings({ ...EngineFormatter.baselineSettings, ...overrides });
        expect(new TextXmlFormatter(rangeSettings).formatXmlPretty(document)).toBe(expected);
    }, 30000);
});

/*
 * Mixed content, and the half of it the engine can be trusted on: what it renders on one line, and
 * a text run it re-indents at the run's own depth. The cases where it writes a newline inside
 * mixed content are deliberately absent - its indentation does not recover from one.
 */
describe("Mixed content matches the engine where the engine is sound (task 8g)", () => {
    const cases: [string, string, Partial<ISettings>][] = [
        ["text on both sides of a child", "<p>some <b>bold</b> text</p>", {}],
        ["several children with text between them", "<p>a <b>x</b> mid <i>y</i> z</p>", {}],
        ["mixed content nested inside mixed content", "<p>a <b>bold <i>it</i> tail</b> z</p>", {}],
        ["a self-closing child inline", "<p>a <br/> b</p>", {}],
        ["a CDATA section inline", "<p>a <![CDATA[raw]]> b</p>", {}],
        ["a comment inline", "<p>a <!-- c --> b</p>", {}],
        ["an inline child carrying attributes", "<p>a <b id=\"1\">x</b> c</p>", {}],
        ["an inline element indented inside a tree", "<r><p>a <b>c</b> d</p><q><s/></q></r>", {}],
        ["mixed content under preserveNewLines", "<p>some <b>bold</b> text</p>", { preserveNewLines: true }],
        ["mixed content among blank-lined siblings", "<r><p>a <b>x</b> c</p><q/><s/></r>", { addEmptyLineBetweenElements: true }],
        ["whitespace between elements is not mixed content", "<p><a/> <b/></p>", {}],
        ["a newline between elements is not mixed content", "<p><a/>\n<b/></p>", {}],
        ["content that is all markup stays a block", "<p><b>x</b><i>y</i></p>", {}],
        ["a text run over several lines", "<p>line one\nline two\nline three</p>", {}],
        ["a text run re-indented at its own depth", "<r><s><p>l1\nl2</p></s></r>", {}],
        ["a text run whose lines arrive ragged", "<r><p>  l1\n      l2  </p></r>", {}],
        ["a text run indented with tabs", "<r><p>l1\n\tl2</p></r>", {}],
        ["a text run at a different indent length", "<r><s><p>l1\nl2</p></s></r>", { indentLength: 2 }],

        // The engine starts a line for a child that does not follow text and glues the rest to it.
        ["markup glued into one line by the text between it", "<r><a/>x<b/></r>", {}],
        ["a child that does not follow text starting a line", "<r><a/>x<b/><c/></r>", {}],
        ["two runs, the second glued by text", "<r><a/><b/>x<c/></r>", {}],
        ["a run glued by text on both sides of a child", "<r><a/>x <b/> y<c/></r>", {}],
        ["a non-breaking space gluing two elements", "<r><a/> <b/></r>", {}],
        ["an element with text content inside a glued run", "<r><a/>x<b>t</b></r>", {}],
        ["leading character data kept on the start tag's line", "<p>some <b>bold</b></p>", {}],
        ["a glued run under a nested element", "<w><r><a/>x<b/></r></w>", {}],
        ["a glued run two levels down", "<w><v><r><a/>x<b/></r></v></w>", {}],
    ];

    it.each(cases)("%s", async (_name, document, overrides) => {
        const expected = await engineOutput(document, overrides);
        const rangeSettings = new Settings({ ...EngineFormatter.baselineSettings, ...overrides });
        expect(new TextXmlFormatter(rangeSettings).formatXmlPretty(document)).toBe(expected);
    }, 30000);
});

/*
 * The other half, pinned so a later engine version cannot change it unnoticed. Once the engine
 * writes a newline inside mixed content its indentation never recovers, and a comment beside text
 * has the indent width injected into the character data. Both are engine bugs worth filing.
 */
describe("Mixed content the engine gets wrong (task 8g)", () => {
    it("indents the root's own end tag once text follows a child", async () => {
        const engine = await engineOutput("<r><s><t><p><b>x</b> c</p></t></s></r>");
        expect(engine).toBe("<r>\n    <s>\n        <t>\n            <p>\n                <b>x</b> c</p>\n            </t>\n        </s>\n    </r>");
        expect(engine.split("\n").at(-1)).toBe("    </r>");
    }, 30000);

    it("writes a following sibling outside its own parent's indentation", async () => {
        expect(await engineOutput("<r><p>a <b>x</b></p><q/></r>")).toBe("<r>\n    <p>a <b>x</b>\n</p>\n<q />\n</r>");
    }, 30000);

    // The injected run grows without bound, and the character data is the user's, not the formatter's.
    it("injects the indent width into character data, and again on every format", async () => {
        const once = await engineOutput("<r><p>a <!-- c --> b</p></r>");
        expect(once).toContain("<p>a     <!-- c --> b</p>");

        const twice = await engineOutput(once);
        expect(twice).toContain("<p>a         <!-- c --> b</p>");
        expect(twice).not.toBe(once);
    }, 30000);

    // Content ending with character data is where the engine glues its end tag and loses the column.
    it.each([
        ["<r><a/>x</r>", "<r>\n    <a />x</r>", "<r>\n    <a />x\n</r>"],
        ["<p><b>bold</b> text</p>", "<p>\n    <b>bold</b> text</p>", "<p>\n    <b>bold</b> text\n</p>"],
        ["<r><a/>x<b/>y</r>", "<r>\n    <a />x<b />y</r>", "<r>\n    <a />x<b />y\n</r>"],
        ["<p>\n    some\n    <b>bold</b>\n    text\n</p>", "<p>\n    some\n<b>bold</b>\n    text\n</p>", "<p>\n    some\n    <b>bold</b>\n    text\n</p>"],
    ])("closes %j on its own line where the engine glues it", async (fragment, engineResult, expected) => {
        expect(await engineOutput(fragment)).toBe(engineResult);

        const formatted = new TextXmlFormatter(settings).formatXmlPretty(fragment);
        expect(formatted).toBe(expected);
        expect(new TextXmlFormatter(settings).formatXmlPretty(formatted)).toBe(formatted);
    }, 30000);

    it("loses the column for good once it glues an end tag, at depth", async () => {
        expect(await engineOutput("<w><r><a/>x</r></w>")).toBe("<w>\n    <r>\n        <a />x</r>\n    </w>");
        // `<b />` belongs at column 8 and `</r>` at 4; the engine writes both at 4 and 0.
        expect(await engineOutput("<w><r>x<a/><b/></r></w>")).toBe("<w>\n    <r>x<a />\n    <b />\n</r>\n</w>");

        expect(new TextXmlFormatter(settings).formatXmlPretty("<w><r><a/>x</r></w>"))
            .toBe("<w>\n    <r>\n        <a />x\n    </r>\n</w>");
    }, 30000);
});
describe("Options the tree unlocks match the engine (task 8d)", () => {
    const indented = "<Root>\n    <A/>\n\n    <B>\n        <C/>\n        <D/>\n    </B>\n    <E><F/><G/><H/></E>\n    <!-- c -->\n    <I>t</I>\n</Root>";
    const commented = "<Root><A/><!-- trailing -->\n    <!-- own line -->\n    <B><!-- first --></B>\n    <C/> <!-- spaced -->\n    <D>t</D><!-- after text element --></Root>";
    const attributes = "<Root a=\"1\" b=\"2\"><Item x=\"1\" y=\"2\"/><Other x=\"1\" y=\"2\"/></Root>";

    const cases: [string, string, Partial<ISettings>][] = [
        ["blank lines between elements", indented, { addEmptyLineBetweenElements: true }],
        ["blank lines only among more than two siblings", "<Root><A><B/><C/></A><D/></Root>", { addEmptyLineBetweenElements: true }],
        ["comment placement", commented, { preserveCommentPlacement: true }],
        ["comment placement, preserving new lines", commented, { preserveCommentPlacement: true, preserveNewLines: true }],
        ["comment placement off", commented, { preserveCommentPlacement: false }],
        ["an exception matching the whole name", attributes, { positionAllAttributesOnFirstLine: true, wildCardedExceptionsForPositionAllAttributesOnFirstLine: ["^Item$"] }],
        ["an exception matching part of the name", attributes, { positionAllAttributesOnFirstLine: true, wildCardedExceptionsForPositionAllAttributesOnFirstLine: ["tem"] }],
        ["an exception matching nothing", attributes, { positionAllAttributesOnFirstLine: true, wildCardedExceptionsForPositionAllAttributesOnFirstLine: ["Nope"] }],
        ["apostrophes escaped", "<Root a=\"it's\" b='x'/>", { allowSingleQuoteInAttributeValue: false }],
        ["apostrophes allowed", "<Root a=\"it's\" b='x'/>", { allowSingleQuoteInAttributeValue: true }],
        ["declaration with a space added", "<?xml version=\"1.0\" encoding=\"utf-8\"?><Root/>", { addSpaceBeforeEndOfXmlDeclaration: true }],
        ["declaration with its space removed", "<?xml version=\"1.0\" encoding=\"utf-8\" ?><Root/>", { addSpaceBeforeEndOfXmlDeclaration: false }],
        ["text and empty elements inline", "<Root><A>t</A><B></B><C><![CDATA[x]]></C></Root>", { useSelfClosingTags: false }],
    ];

    it.each(cases)("%s", async (_name, document, overrides) => {
        const expected = await engineOutput(document, overrides);
        const rangeSettings = new Settings({ ...EngineFormatter.baselineSettings, ...overrides });
        expect(new TextXmlFormatter(rangeSettings).formatXmlPretty(document)).toBe(expected);
    }, 30000);
});

/*
 * The findings that decide whether delegating to the engine is worth building, pinned as tests so
 * a later engine version cannot quietly change the answer.
 */
describe("Delegating a selection to the engine - what the synthetic root can and cannot do", () => {
    const wholeDocuments = [
        "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>",
        "<Root><!-- lead --><Child a=\"1\" b=\"2\">text</Child><Empty/><![CDATA[x]]></Root>",
        "<a><b><c><d><e>deep</e></d></c></b></a>",
    ];

    it.each(wholeDocuments)(
        "a synthetic root added and stripped reproduces the engine's own document formatting: %s",
        async document => {
            const direct = await engineOutput(document);
            const enclosed = await engineOutput(FragmentRepairer.repair(document).document);
            expect(FragmentRepairer.stripSyntheticRoot(enclosed, indentLength)).toBe(direct);
        },
        30000
    );

    it("formats a fragment whose namespace prefix is bound outside the selection", async () => {
        const repaired = FragmentRepairer.repair("<xsl:template match=\"/\"><xsl:text>x</xsl:text></xsl:template>");
        expect(repaired.syntheticPrefixes).toContain("xsl");

        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toBe("<xsl:template match=\"/\">\n    <xsl:text>x</xsl:text>\n</xsl:template>");
    }, 30000);

    /*
     * One xmlns per prefix puts the synthetic root past attributesInNewlineThreshold, so the
     * engine wraps the synthetic root's own start tag - and a stripper that assumes that root
     * occupies one line leaves two stray xmlns lines at the top of the user's selection.
     */
    it("strips a synthetic root whose own start tag wrapped over several lines", async () => {
        const repaired = FragmentRepairer.repair("<d:Grid x:Name=\"root\" m:Ignorable=\"d\"><d:Text/></d:Grid>");
        expect(repaired.syntheticPrefixes).toEqual(["d", "m", "x"]);

        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).not.toContain("prettyxml-synthetic");
        expect(formatted.split("\n")[0]).toBe("<d:Grid x:Name=\"root\"");
    }, 30000);

    it("keeps a prefix the fragment declares itself bound to the real namespace", async () => {
        const repaired = FragmentRepairer.repair("<a xmlns:p=\"urn:x\"><p:b/></a>");
        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toContain("xmlns:p=\"urn:x\"");
    }, 30000);

    it("refuses an unbalanced selection rather than inventing the missing tags", () => {
        expect(FragmentRepairer.repair("</b></a>").rejection).toContain("unbalanced");
        expect(FragmentRepairer.repair("<a><b>text").rejection).toContain("unbalanced");
    });

    it("refuses a selection that ends mid-tag", () => {
        expect(FragmentRepairer.repair("<a><b attr=\"v").rejection).toContain("mid-token");
    });

    it("cannot format a selection referencing an entity declared outside it", async () => {
        const repaired = FragmentRepairer.repair("<a>&myEntity;</a>");
        expect(repaired.rejection).toBe("");

        const result = await EngineFormatter.run(repaired.document);
        expect(result.exitCode).not.toBe(0);
        expect(EngineFormatter.describeFailure(result)).toBe("Reference to undeclared entity 'myEntity'.");
    }, 30000);

    /*
     * The engine normalizes an attribute value the user did not ask to have rewritten. That is
     * correct XML and wrong for a selection, and it is the strongest argument for the tree
     * formatter owning the default path: rule 1 says nothing is invented and nothing is deleted.
     */
    it("rewrites attribute value bytes that the range formatter leaves alone", async () => {
        const repaired = FragmentRepairer.repair("<a b=\"x>y\" c='say \"hi\"'/>");
        const formatted = FragmentRepairer.stripSyntheticRoot(await engineOutput(repaired.document), indentLength);
        expect(formatted).toContain("&gt;");
        expect(formatted).toContain("&quot;");
    }, 30000);
});
